version: "3.0"

services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        expose:
            - 5432
        networks:
            - cz_biohub_network
        restart: always

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - "./backend:/usr/src/backend"
        networks:
            - cz_biohub_network
        ports:
            - 5000:5000
        environment:
            - FLASK_ENV=development
        depends_on:
            - db
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - cz_biohub_network
        environment:
            - NODE_ENV=development
        depends_on:
            - backend

networks:
    cz_biohub_network:
        driver: bridge