version: "3.0"

services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        expose:
            - 5432
        networks:
            - cz_biohub_network
        restart: always